Update README.md to clarify version support and add headers where app…
GeyserMC/Hurricane pull request #23
Opened 2024-06-03 00:38 UTC by BrailleBennett

…licable

2024-06-19 10:47 UTC, onebeastchris requested changes

2024-06-19 10:47 UTC, onebeastchris commented on README.md
> +- 1.17.x - 1.19.x for pig riding
```suggestion
- 1.17.x - 1.19.x for pig/strider riding
```

2024-06-19 10:47 UTC, onebeastchris commented on README.md
> +- 1.14.x - 1.20.x for bamboo and dripstone fix
```suggestion
- 1.14.x - 1.20.x for bamboo and dripstone collision fixes 
```

2024-06-19 10:47 UTC, onebeastchris commented on README.md
> -- https://github.com/GeyserMC/Geyser/issues/638 by implementing the control server-side. (Doesn't work on 1.20+)
Why was this removed? That's not yet resolved - unless you intend to wait with this PR until that issue was resolved? For the latter, I'd turn this PR into a draft until then.

2024-06-19 11:01 UTC, BrailleBennett commented on README.md
> -- https://github.com/GeyserMC/Geyser/issues/638 by implementing the control server-side. (Doesn't work on 1.20+)
I removed the link to the issue and described what the fix did in words to make it easier to understand for the average user what exactly was being fixed. Should I link the resolved issue as well as having the human readable text?

2024-06-19 11:02 UTC, onebeastchris commented on README.md
> -- https://github.com/GeyserMC/Geyser/issues/638 by implementing the control server-side. (Doesn't work on 1.20+)
Yep, that'd be ideal.

2024-06-19 11:14 UTC, BrailleBennett commented
Can we check if bamboo and drip stone is functional in 1.21? If so, I can update the line that refrences the supported versions.

2024-07-22 22:35 UTC, onebeastchris commented
Bamboo/Dripstone is still functional from my brief testing

2024-07-22 22:36 UTC, onebeastchris approved these changes

2024-07-22 22:36 UTC, onebeastchris commented on README.md
> +- 1.14.x - 1.20.x for bamboo and dripstone collision fixes
```suggestion
- 1.14.x - 1.21 for bamboo and dripstone collision fixes 
```

2024-07-22 22:37 UTC, merged